services:
  # Backend Service (Development)
  backend-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=sqlite:///./jiuwen_studio_dev.db
      - SECRET_KEY=dev-secret-key
      - DEBUG=true
    volumes:
      - ../backend:/app
      - /app/__pycache__
    depends_on:
      - postgres-dev
      - redis-dev
    networks:
      - jiuwen-backend-network
    restart: unless-stopped

  # PostgreSQL Database (Development)
  postgres-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=jiuwen_studio_dev
      - POSTGRES_USER=jiuwen_dev_user
      - POSTGRES_PASSWORD=jiuwen_dev_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - jiuwen-backend-network
    restart: unless-stopped

  # Redis Cache (Development)
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - jiuwen-backend-network
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  jiuwen-backend-network:
    driver: bridge